# Generated by Django 5.2.8 on 2026-09-04 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("bathroom", "Bathroom"),
                            ("living", "Living"),
                            ("trash", "Trash"),
                            ("laundry", "Laundry"),
                            ("outdoor", "Outdoor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("effort", models.PositiveSmallIntegerField(default=3)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Estimated minutes", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "rrule",
                    models.CharField(
                        blank=True, help_text="RFC5545 rrule or empty", max_length=200
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof",
                    models.FileField(blank=True, null=True, upload_to="proofs/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
                "indexes": [
                    models.Index(
                        fields=["household", "status", "due_at"],
                        name="chores_chor_househo_806573_idx",
                    ),
                    models.Index(
                        fields=["assignee"], name="chores_chor_assigne_a43dfe_idx"
                    ),
                ],
            },
        ),
    ]
